[package]
name = "methodray"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "methodray"
path = "src/lib.rs"

[dependencies]
methodray-core = { path = "../rust", features = ["ruby-ffi"] }
magnus = "0.8"
